image: gradle:5.6.4-jdk8

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - pwd
    - ls
    - ./gradlew compileJava
    - ./gradlew clean assemble

test:
  stage: test
  script:
    - ./gradlew check 