before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build  
  image: 
    name: gradle:5.6.4-jdk8  
  script:    
    - ./gradlew compileJava
    - ./gradlew clean assemble   

test:
  stage: test
  tags:
    - automatizacion
  image:
    name: registry.gitlab.com/red5g/finsonet/app/sqa_code
  script:
    - echo $COMMAND_GRADLE
    - $COMMAND_GRADLE
    - ls -R    
  artifacts:
    when: always
    paths:      
      - ./target/site/serenity/      
      - ./build/reports/tests/test/index.html
    expire_in: 1 week
  allow_failure: true
