image: gradle:5.6.4-jdk8

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  tags:
    - automatizacion

  script:    
    - ./gradlew clean compileJava
    - chmod 777 chromedriver

test:
  stage: test
  tags:
    - automatizacion
  script:
    - echo $COMMAND_GRADLE
    - $COMMAND_GRADLE 